# Generated by Django 5.2 on 2026-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="ID пользователя в Telegram для получения уведомлений",
                max_length=50,
                null=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
